feat: Complete user signup
wwh-techcamp-2018/team5-fiveMasterGuys pull request #52
Opened 2018-08-16 13:15 UTC by minzzzy

Resolves: #16

2018-08-16 13:31 UTC, Lahavas commented on src/main/java/com/woowahan/techcamp/recipehub/user/domain/UserRepository.java
> +    Boolean existsByEmail(String email);
따로 이유가 없다면 Boolean Class보단 boolean Type으로 Return하는게 좋을듯합니다

2018-08-16 13:31 UTC, Lahavas commented on src/main/resources/static/js/users/signup.js
> +            console.log(name);
console.log는 빼도 괜찮을거같슴니다~

2018-08-16 13:58 UTC, CHANMYUNG requested changes
구현 잘 했네요.

2018-08-16 13:58 UTC, Nooheat commented on src/main/java/com/woowahan/techcamp/recipehub/user/controller/UserRestController.java
> +        userService.add(dto);
add보다는 create나 있는 그대로 signup이 어떨까요?

2018-08-16 14:15 UTC, Nooheat commented on src/main/resources/templates/users/login.hbs
> +<script src="/js/users/login.js"></script>
수고하셨어요 ㅠㅠ 죄송합니다 ㅋㅋ

2018-08-16 18:39 UTC, ryuneeee approved these changes
좋아요. 전 Approve!

2018-08-16 18:39 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/user/controller/UserRestController.java
> +    public void signup(@Valid @RequestBody SignupDto dto) {
Return이 빠진것 같아요~ 😢 이걸 void로 해야 맞을까요?

2018-08-16 18:39 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/user/service/UserService.java
> +        }
이거 한 줄로 줄일수도 있을 것 같아요!
특정 유저가 존재하는지를 알려면 DB에 어떤 Query를 날려야 할까요? 
또, JPA는 existsByEmail에 대해서 어떤 Query를 만들어낼까요?

내일 같이 고민해봐요~

2018-08-16 18:39 UTC, ryuneeee commented on src/test/java/com/woowahan/techcamp/recipehub/user/service/UserServiceTest.java
> +    private PasswordEncoder passwordEncoder;
userRepository와 passwordEncoder가 서로 크...크로스가 되었습니다! 멋져요👍

2018-08-16 18:39 UTC, ryuneeee commented on src/main/resources/static/js/users/signup.js
> +                onSuccess: () => {
ArrowFunction 적극사용 좋아요좋아요🙏

2018-08-16 18:39 UTC, ryuneeee commented on src/main/resources/static/js/users/signup.js
> +            fetchManager({
장기적으로 생각해 본다면 registerEvents()가 fetchManager까지 관심을 가져야할까요?
지금은 코드가 길지 않으니 괜찮지만, 한 번쯤 생각해보기~ 
(디테일한 코드를 보지 않고 어떤 이벤트를 등록하는지 어떻게 의도를 드러낼지도 고민해봅시당🧐)

2018-08-16 18:39 UTC, ryuneeee commented on src/test/java/com/woowahan/techcamp/recipehub/user/dto/SignupDtoTest.java
> +        assertConstraintViolations(signupDtoBuilder.build(), 0);
기본적인 사용 테스트 굿✌️ 이러면 별도의 문서가 필요 없죠

2018-08-16 18:39 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/user/controller/UserController.java
> +            return "redirect:/";
최고 👻 👍 👀🧠

2018-08-16 18:39 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/user/dto/SignupDto.java
> +    @AssertTrue(message = "")
1. Validation을 위한 @AssertTrue Annotation👍 줍줍합니다
이거 찾아봤는데 저도 잘 감이 안와서, 내일 설명 부탁드릴게요🙏
2. matchPassword는 다른데서 쓰지 않는것 같아요. (사용한다면, 테스트 케이스 만들어주시면 감사!)

2018-08-17 05:03 UTC, minzzzy commented on src/main/java/com/woowahan/techcamp/recipehub/user/domain/UserRepository.java
> +    Boolean existsByEmail(String email);
이해했습니다. 수정할께요

2018-08-17 05:06 UTC, minzzzy commented on src/main/java/com/woowahan/techcamp/recipehub/user/controller/UserRestController.java
> +    public void signup(@Valid @RequestBody SignupDto dto) {
그렇군요. 나중에 response model이 생기면 생성된 user에 대한 정보를 응답으로 보내는 것이 좋을까요?

2018-08-17 05:08 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/user/controller/UserRestController.java
> +    public void signup(@Valid @RequestBody SignupDto dto) {
Cool 🏝

2018-08-17 06:22 UTC, ffaass approved these changes

2018-08-17 06:24 UTC, Lahavas approved these changes
승인합니다~

2018-08-17 06:30 UTC, CHANMYUNG approved these changes

2018-08-17 06:49 UTC, merged