feat: Show completed recipe view
wwh-techcamp-2018/team5-fiveMasterGuys pull request #53
Opened 2018-08-16 13:44 UTC by ffaass

Resolves: #8

2018-08-16 14:13 UTC, CHANMYUNG requested changes
구현 잘 했네요. 리뷰했어요.

2018-08-16 14:13 UTC, Nooheat commented on src/main/java/com/woowahan/techcamp/recipehub/RecipehubApplication.java
> +	public static void main(String[] args) {
6 spaces indentation이네요?

2018-08-16 14:13 UTC, Nooheat commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/domain/AbstractRecipeStep.java
> +@DiscriminatorColumn(name="type")
여기 왜? 혹시 reformat code하고 optimize import 안하셨나용??

2018-08-16 14:48 UTC, Lahavas commented on src/main/java/com/woowahan/techcamp/recipehub/common/Template.java
> +    public static final String RECIPE_COMPLETED = "/recipe-completed";
여기 클래스명이 살짝 모호하다고 생각됩니다. 추후에 팀원들과 함께 논의해볼 필요가 있을거같습니다~

2018-08-16 14:48 UTC, Lahavas commented on src/main/resources/data-local.sql
> +INSERT INTO recipe_step (type, content, img_url, name, closed, sequence, rejected, recipe_id, writer_id) VALUES ('Step', '[''빵을 얹는다'']', 'https://cdn.bmf.kr/_data/product/IF088/2dee3415155804a5e9dc7c
위의 recipe & recipe_step 더미데이터랑 잘 구분이 안되는거같습니다.

2018-08-16 14:48 UTC, Lahavas commented on src/main/resources/templates/index.hbs
> +    <div class="container">
여기 reformat code 잘못 먹힌거같네요 Indent가 잘못 들어갔습니다~

2018-08-16 14:48 UTC, Lahavas commented on src/main/resources/templates/recipe-completed.hbs
> +    <div class="container">
base.hbs에 contents 바깥 부분에 body Tag가 정의되어있지 않아서 이 부분은 body Tag로 감싸줘야할거같네요~

2018-08-16 14:48 UTC, Lahavas commented on src/main/resources/templates/recipe-incompleted.hbs
> +    <div class="container">
base.hbs에 contents 바깥 부분에 body Tag가 정의되어있지 않아서 이 부분은 body Tag로 감싸줘야할거같네요~

2018-08-16 18:41 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/RecipehubApplication.java
> +	public static void main(String[] args) {
이거 아마 Tab이 Spacing으로 안되는거 같아요. \t 문자로 보이네요

2018-08-16 18:52 UTC, ryuneeee requested changes
findById만 수정 해 주시면 될듯😇

2018-08-16 18:52 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/domain/Recipe.java
> +        this.recipeSteps = this.recipeSteps.stream()
기존 Variable에 덮어쓰는건 좋지 않아요~

2018-08-16 18:52 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/domain/Recipe.java
> +        this.recipeSteps = this.recipeSteps.stream()
아, 구조상 그런거구나. 이것도 논의를 하는 방향으로 가볼까요

2018-08-16 18:52 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/service/RecipeService.java
> +    private RecipeRepository recipeRepository;
제가 놓친거 잘 챙겨주셨네 ㅋㅋㅋㅋ🤩

2018-08-16 18:52 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/service/RecipeService.java
> +            recipe.removeClosedSteps();
Entity를 find를 하는 과정에서, Entity를 수정하는건 좀 이상한거 같아요🧐

2018-08-16 18:52 UTC, ryuneeee commented on src/main/resources/data-local.sql
> +INSERT INTO recipe_step (type, content, img_url, name, closed, sequence, rejected, recipe_id, writer_id) VALUES ('Step', '[''빵을 얹는다'']', 'https://cdn.bmf.kr/_data/product/IF088/2dee3415155804a5e9dc7c
SQL 주석 달아주시면 감사!

2018-08-16 23:20 UTC, Lahavas commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/domain/Recipe.java
> +        this.recipeSteps = this.recipeSteps.stream()
저도 이부분 고민되더라구요 논의해보져~

2018-08-17 00:27 UTC, Lahavas commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeController.java
> +public class RecipeController {
여기 개인적인 의견으로는.... recipe보단 recipes로 Routing을 지정하는게 더 좋을거같네요

2018-08-17 01:08 UTC, nigayo commented
오 엄격한 리뷰!

2018-08-17 06:55 UTC, minzzzy approved these changes
저는 승인합니다~

2018-08-17 06:55 UTC, minzzzy commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/dto/RecipeCreationDTO.java
> +    public RecipeCreationDTO(@NotNull Category category, @NotEmpty @NotNull String name, String imgUrl) {
생성자를 만들어 줄 때도 NotNull과 같은 annotation을 붙여줘야 하나요? 불필요하면 빼줘도 좋을 것 같습니다.

2018-08-17 07:02 UTC, CHANMYUNG approved these changes
제가 이슈 쳐내기 바빠서요 ㅎㅎ;; 
양심선언합니다.
"저 바뀐 코드 리뷰 안했어요"

2018-08-17 07:04 UTC, Nooheat commented
컨플릭트 뭔가요!!

2018-08-17 07:16 UTC, ryuneeee approved these changes

2018-08-17 07:16 UTC, Lahavas approved these changes
승인할게요

2018-08-17 07:16 UTC, merged