feat: Parse recipestep contents
wwh-techcamp-2018/team5-fiveMasterGuys pull request #68
Opened 2018-08-18 11:56 UTC by ffaass

Step에 대한 DTO를 만들어서 '["빵을 놓는다","고기를 올린다"]' 형식의 String을 List로 변환해서 View로 전달함
이후에 스텝 추가/수정시에도 JS에서 JSON string을 만들 필요 없이 JSON Array를 서버로 전달하면 DTO 재사용 가능

Resolves: #67

2018-08-18 12:19 UTC, CHANMYUNG approved these changes
구현 잘 했어요. Approve합니다.

2018-08-19 04:10 UTC, Lahavas reviewed
JSON과 String을 변환하는 동작에 대하여 Convert라는 단어와 Parse라는 단어가 혼용되는것같습니다. 구현에 대해서는 흠잡을 부분이 없네요 💯

2018-08-19 04:21 UTC, Lahavas approved these changes

2018-08-19 05:59 UTC, ryuneeee requested changes
Annotation 이용한 컨버터 만들어주세요~

2018-08-19 05:59 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverter.java
> +public class RecipeStepContentJsonConverter implements RecipeStepContentConverter {
지금 단계에서는 무분별한 확장 설계로 보여요.
interface로 추상화 시키는건, Converter가 두개 이상일 시점에 다시 고민해봐도 될 듯 해요~

2018-08-19 05:59 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverter.java
> +            return objectMapper.readValue(content, new TypeReference<List<String>>() {
이 클래스에서 상태를 가지고 있을 필요가 없을것 같은데, 클래스 안쪽에 method들을 다 static으로 만들어도 되지 않을까요?
예를 들어서 이런거죠.

ContentConverter.*toList*(content);

2018-08-19 05:59 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverter.java
> +            return objectMapper.writeValueAsString(contents);
이것도 마찬가지로

ContentConverter.*toContentString*(contents);

2018-08-19 05:59 UTC, ryuneeee commented on src/test/java/com/woowahan/techcamp/recipehub/recipestep/dto/RecipeStepDTOTest.java
> +        assertThat(recipeStepDTO.getRecipe()).isEqualTo(recipeStep.getRecipe());
이렇게 많이 비교하면 두 객체를 비교하는 method를 두개 중 하나의 클래스에 만들어도 될 것 같아요. 
왠지 만들어 두면 쓸 것 같은 느낌?

2018-08-19 05:59 UTC, ryuneeee commented on src/test/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverterTest.java
> +        contentList = Arrays.asList("식빵을 토스터기에 굽는다", "잼을 바른다");
Arrays.asList 굿👍

2018-08-19 05:59 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverter.java
> +public class RecipeStepContentJsonConverter implements RecipeStepContentConverter {
http://wonwoo.ml/index.php/post/995
자 Converter를 어-노테이션으로 만들어 봅시다! 
어차피 밑에서 리뷰한 것 처럼 Static Class로 만들 수 있다면, 고고

2018-08-19 06:35 UTC, ffaass commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverter.java
> +public class RecipeStepContentJsonConverter implements RecipeStepContentConverter {
오호 이런게 있었네요!
이걸 쓰게 되면 entity 객체에서도 List로 들고 있을 수 있겠네요 ㅎㅎ 
그러면 DTO에서 별도의 변환 로직을 호출하지 않고도 원하던 기능을 구현할 수 있을 것 같네요!
오늘은 저녁까진 작업이 힘들고, 밤이나 내일쯤 바꿔서 다시 푸시해볼게요~

2018-08-19 06:40 UTC, ffaass commented on src/main/java/com/woowahan/techcamp/recipehub/recipestep/util/RecipeStepContentJsonConverter.java
> +public class RecipeStepContentJsonConverter implements RecipeStepContentConverter {
인터페이스로 뺀 이유가 있었는데 피드백받고 다시 생각해보니 저장되는 데이터에 버전이 생기는 경우 말고는 추상화할 이유가 딱히 없네요 ㅋㅋㅋㅋ 같이 수정해서 올릴게요!

2018-08-20 06:19 UTC, ffaass commented on src/test/java/com/woowahan/techcamp/recipehub/recipestep/dto/RecipeStepDTOTest.java
> +        assertThat(recipeStepDTO.getRecipe()).isEqualTo(recipeStep.getRecipe());
비교는 아직 이 테스트에서밖에 하고있지 않아서 메서드를 만들진 않았는데, equals로 비교 가능하게 하는건 어떻게 생각하시나요?

2018-08-20 06:41 UTC, Lahavas approved these changes

2018-08-20 06:41 UTC, Lahavas commented on src/main/java/com/woowahan/techcamp/recipehub/RecipehubConfig.java
> +
한줄 추가되어있네여

2018-08-20 06:49 UTC, minzzzy approved these changes

2018-08-20 06:50 UTC, ryuneeee approved these changes
일단 저도 승인합니다 ~

2018-08-20 06:50 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/recipe/dto/RecipeResponseDTO.java
> +                        stepStream.map(RecipeStepDTO::from).collect(Collectors.toList())
이거 collectors.toList mutable이라서, 혹시나 immutable로 바꿀 수 있다면 해주고, 아니면 너무 시간은 버리지 맙시다

2018-08-20 06:50 UTC, ryuneeee commented on src/main/java/com/woowahan/techcamp/recipehub/RecipehubConfig.java
> +
이거 너무 가혹한거 아닙니까 ㅋㅋㅋㅋㅋ 사람이 여유도 가지고 좀 그래야 ... 🎻🎺🏝

2018-08-20 06:51 UTC, merged